queries:
  - exclude: cpp/integer-multiplication-cast-to-long
  - exclude: cpp/missing-header-guard
  - exclude: cpp/short-global-name
  - exclude: cpp/uncontrolled-allocation-size
  - exclude: cpp/tainted-format-string
  - exclude: cpp/tainted-format-string-through-global
  - exclude: cpp/toctou-race-condition
