// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef SelfCertApp_h
#define SelfCertApp_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tile.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>

/**
 Self-Certification application window
*/
class SelfCertApp {
public:
  SelfCertApp();
private:
  Fl_Double_Window *window;
  Fl_Tile *tile;
  Fl_Browser *browser;
  Fl_Group *results;
  Fl_Browser *resultsBrowser;
  Fl_Button *resultsSubmit;
  Fl_Button *resultsCancel;
public:
  ~SelfCertApp();
  void show(int argc, char *argv[]);
  bool test(const char *name);
};
#endif
