// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "SelfCertApp.h"

/**
 Constructor
*/
SelfCertApp::SelfCertApp() {
  { window = new Fl_Double_Window(600, 500, "IPP Everywhere\342\204\242 Printer Self-Certification Tool v2.0");
    window->user_data((void*)(this));
    window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { tile = new Fl_Tile(0, 0, 600, 500);
      { browser = new Fl_Browser(0, 0, 600, 100);
      } // Fl_Browser* browser
      { results = new Fl_Group(0, 100, 600, 400);
        { resultsBrowser = new Fl_Browser(0, 100, 600, 365);
          resultsBrowser->textfont(4);
          Fl_Group::current()->resizable(resultsBrowser);
        } // Fl_Browser* resultsBrowser
        { resultsSubmit = new Fl_Button(450, 470, 65, 25, "Submit");
        } // Fl_Button* resultsSubmit
        { resultsCancel = new Fl_Button(525, 470, 65, 25, "Cancel");
        } // Fl_Button* resultsCancel
        results->end();
        Fl_Group::current()->resizable(results);
      } // Fl_Group* results
      tile->end();
      Fl_Group::current()->resizable(tile);
    } // Fl_Tile* tile
    window->end();
  } // Fl_Double_Window* window
}

SelfCertApp::~SelfCertApp() {
  delete window;
}

void SelfCertApp::show(int argc, char *argv[]) {
  window->show(argc, argv);
}
