name: ippeveselfcert
base: core22
version: "2.0.0"
summary: IPP Everywhere™ Printer Self-Certification Tools
description: |
  This snap provides IPP Everywhere™ Printer Self-Certification tools for Linux.

grade: stable
confinement: strict
icon: selfcert/ipp-everywhere.png

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
    ippevetool:
        extensions: [gnome]
        command: bin/ippevetool
        desktop: share/applications/ippevetool.desktop
        plugs: [avahi-observe, home, network]
    ippeveprinter:
        command: bin/ippeveprinter
        plugs: [avahi-observe, home, network, network-bind]
    ippfind:
        command: bin/ippfind
        plugs: [avahi-observe, home, network]
    ipptool:
        command: bin/ipptool
        plugs: [home, network]

parts:
    main:
        plugin: autotools
        source: .
        source-submodules: [libcups]
        build-packages: [libavahi-client-dev, libssl-dev, zlib1g-dev]
        stage-packages: [libavahi-client3]
