name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout ippeveselfcert sources
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Update build environment
      run: sudo apt-get update --fix-missing -y
    - name: Install prerequisites
      run: sudo apt-get install -y avahi-daemon cppcheck libavahi-client-dev libjpeg-dev libpam-dev libpng-dev libssl-dev libusb-1.0-0-dev zlib1g-dev
    - name: Configure ippeveselfcert
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer --with-sanitizer=address --enable-static --disable-shared
    - name: Build ippeveselfcert
      run: make
#     - name: Test ippeveselfcert
#       run: make test

  build-macos:

    runs-on: macos-latest

    steps:
    - name: Checkout ippeveselfcert sources
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install prerequisites
      run: brew install cppcheck fltk libjpeg libpng libusb openssl
    - name: Configure ippeveselfcert
      run: ./configure --enable-debug --enable-maintainer --with-sanitizer=address --enable-static --disable-shared
    - name: Build ippeveselfcert
      run: make
#     - name: Test ippeveselfcert
#       run: make test

  build-windows:

    runs-on: windows-latest

    steps:
    - name: Checkout ippeveselfcert sources
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Restore NuGet packages
      run: cd vcnet; nuget restore ippeveselfcert.sln; cd ..\libcups\vcnet; nuget restore libcups.sln
    - name: Build ippeveselfcert
      run: cd vcnet; msbuild ippeveselfcert.sln
